version: '2.1'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on: 
      eureka:
        condition: service_healthy
    environment:
      - EUREKA_URL=http://eureka:8761/eureka

  eureka:
    image: nadchel/eureka-server:1.0
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://eureka:8761"]
      interval: 10s
      timeout: 10s
      retries: 10
