# Actuator
management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, mappings, gateway
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    gateway:
      enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui
    config-url: /swagger-ui/config

gateway:
  servers:
    - url: https://localhost:8080
      description: Dynamic-Gateway
  versionPrefix: /api/v1
  publicPatterns:
    - /api/v1/registration/**
    - /api/v1/login/**
    - /actuator/**
    - /swagger-ui/**
    - /webjars/**
    - /doc/*
  ignoredPatterns:
    - /error/**
