server:
  port: 8080

# Actuator
management:
  endpoints:
    web:
      exposure.include: beans, env, health, info, mappings, gateway
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true
    gateway:
      enabled: true
  health:
    livenessState:
      enabled: true
    readinessState:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true
    non-secure-port-enabled: false
    secure-port-enabled: true

gateway:
  servers:
    - url: http://localhost:${server.port}
      description: Dynamic-Gateway
  versionPrefix: /api/v1
  publicPatterns:
    - /api/v1/signup
    - /api/v1/login
    - /actuator/**
    - /swagger-ui/**
    - /webjars/**
    - /doc/*
    - /fallback/**
  ignoredPatterns:
    - /error/**
  ignoredPrefixes:
    - /auth
